# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17DZj-nrOfyR0U5R-ASSxcuL0niaPTJLt
"""

import streamlit as st
import matplotlib.pyplot as plt
from utils import predict_class

st.title("🐱🐶 Cat vs Dog Classifier")
uploaded_file = st.file_uploader("Upload an image", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    st.image(uploaded_file, use_column_width=True)

    if st.button("Classify"):
        image_bytes = uploaded_file.read()
        label, confidence = predict_class(image_bytes)
        st.markdown(f"### Prediction: *{label}* ({confidence:.2f} confidence)")

        # Visualize confidence
        fig, ax = plt.subplots()
        ax.bar(["Cat", "Dog"], [confidence, 1-confidence] if label == "Cat" else [1-confidence, confidence])
        st.pyplot(fig)





# Commented out IPython magic to ensure Python compatibility.
# %pip install opencv-python tensorflow matplotlib numpy streamlit

streamlit run app.py

git init
git add .
git commit -m "Cat vs Dog Classifier with OpenCV and TensorFlow"
git remote add origin https://github.com/your-username/cat-dog-classifier.git
git push -u origin main