# -*- coding: utf-8 -*-
"""utils

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ReI9gOtjsb71bzZpa3kp0oZXDv3CLSG
"""

import cv2
import numpy as np
from tensorflow.keras.models import load_model

model = load_model("model/cat_dog_model.h5")

def preprocess_image(image_bytes):
    image = cv2.imdecode(np.frombuffer(image_bytes, np.uint8), cv2.IMREAD_COLOR)
    image = cv2.resize(image, (100, 100))
    image = image / 255.0
    return np.expand_dims(image, axis=0)

def predict_class(image_bytes):
    image = preprocess_image(image_bytes)
    pred = model.predict(image)[0]
    return ("Cat", pred[0]) if pred[0] > pred[1] else ("Dog", pred[1])